version: '3.4'

networks:
    production-network:
        driver: bridge

services:
  filmesscrappingapi:
    image: ${DOCKER_REGISTRY-}filmesscrappingapi
    build:
      context: .
      dockerfile: FilmesScrappingApi/Dockerfile
    ports:
    - "7003:80"
    - "7004:443"
    networks:
      - production-network
    #environment:
    #    MongoDbSettigns_ConnectionString: 'mongodb://admin:abc123!@filmes.db'
    depends_on:
       - mongodb

  mongodb:
    image: mongo
    networks:
      - production-network
    ports:
      - '2019:2017'
    container_name: mongo-api
    command: mongod --port 27017 --bind_ip 0.0.0.0
    #environment:
    #   MONGO_INITDB_ROOT_USERNAME: 'admin'
    #   MONGO_INITDB_ROOT_PASSWORD: 'abc123!'